/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pandelitosecommercewebsite;

/**
 *
 * @author Paolo
 */
public class Cart extends javax.swing.JFrame
{

    /**
     * Creates new form Cart
     */
    public Cart()
    {
        initComponents();
        setTitle("Cart");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        productName1 = new javax.swing.JLabel();
        removeFromCart1 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        totalPrice = new javax.swing.JLabel();
        toCheckout = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        productName2 = new javax.swing.JLabel();
        productImage1 = new javax.swing.JLabel();
        productAmount1 = new javax.swing.JLabel();
        productPrice1 = new javax.swing.JLabel();
        removeFromCart2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        productName = new javax.swing.JLabel();
        productImage = new javax.swing.JLabel();
        productAmount = new javax.swing.JLabel();
        productPrice = new javax.swing.JLabel();
        removeFromCart = new javax.swing.JLabel();

        productName1.setText("ProductName");

        removeFromCart1.setText("RemoveFromCart");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backButton.setText("Back");
        backButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, -1, -1));

        totalPrice.setText("TotalPrice");
        getContentPane().add(totalPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 400, -1, -1));

        toCheckout.setText("Proceed to checkout");
        toCheckout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toCheckout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toCheckoutActionPerformed(evt);
            }
        });
        getContentPane().add(toCheckout, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 440, -1, -1));

        productName2.setText("ProductName");

        productImage1.setText("ProductImage");

        productAmount1.setText("ProductAmount");

        productPrice1.setText("ProductPrice");

        removeFromCart2.setText("RemoveFromCart");

        productName.setText("ProductName");

        productImage.setText("ProductImage");

        productAmount.setText("ProductAmount");

        productPrice.setText("ProductPrice");

        removeFromCart.setText("RemoveFromCart");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(productImage)
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(removeFromCart)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(productName)
                        .addGap(52, 52, 52)
                        .addComponent(productAmount)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(productPrice)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productName)
                    .addComponent(productImage)
                    .addComponent(productAmount)
                    .addComponent(productPrice))
                .addGap(18, 18, 18)
                .addComponent(removeFromCart)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(productImage1)
                .addGap(76, 76, 76)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeFromCart2)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(productName2)
                        .addGap(52, 52, 52)
                        .addComponent(productAmount1)
                        .addGap(56, 56, 56)
                        .addComponent(productPrice1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(productName2)
                    .addComponent(productImage1)
                    .addComponent(productAmount1)
                    .addComponent(productPrice1))
                .addGap(18, 18, 18)
                .addComponent(removeFromCart2)
                .addGap(38, 38, 38)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 560, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_backButtonActionPerformed
    {//GEN-HEADEREND:event_backButtonActionPerformed
        this.setVisible(false);
        new ViewProductsPage().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void toCheckoutActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_toCheckoutActionPerformed
    {//GEN-HEADEREND:event_toCheckoutActionPerformed
        this.setVisible(false);
        new DeliveryAddress().setVisible(true);
    }//GEN-LAST:event_toCheckoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Cart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Cart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel productAmount;
    private javax.swing.JLabel productAmount1;
    private javax.swing.JLabel productImage;
    private javax.swing.JLabel productImage1;
    private javax.swing.JLabel productName;
    private javax.swing.JLabel productName1;
    private javax.swing.JLabel productName2;
    private javax.swing.JLabel productPrice;
    private javax.swing.JLabel productPrice1;
    private javax.swing.JLabel removeFromCart;
    private javax.swing.JLabel removeFromCart1;
    private javax.swing.JLabel removeFromCart2;
    private javax.swing.JButton toCheckout;
    private javax.swing.JLabel totalPrice;
    // End of variables declaration//GEN-END:variables
}
