/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pandelitosecommercewebsite;

import javax.swing.table.DefaultTableModel;
import static pandelitosecommercewebsite.Cart.products;

/**
 *
 * @author Noah Peñaranda
 */
public class ConfirmationPage extends javax.swing.JFrame {

    /**
     * Creates new form ConfirmationPage
     */
    
    public ConfirmationPage() {
        initComponents();
        setTitle("Purchase Completion");
        
        //table
        DefaultTableModel model = (DefaultTableModel)TableProductsInCart.getModel();
        for (CartItem product : products)
        {
            model.addRow(new Object[]{product.productName, product.productAmount,"P " + product.productPrice * product.productAmount});
        }
        
        //total price
        double totalPrice = 0;
        
        for (CartItem product : products)
        {
            double temp = product.productAmount * product.productPrice;
            totalPrice += temp;
        }
        totalPriceLabel.setText("Total Price: P " + totalPrice); 
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        thankYouLabel = new javax.swing.JLabel();
        productsPurchasedLabel = new javax.swing.JLabel();
        totalPriceLabel = new javax.swing.JLabel();
        purchaseConfirmedLabel1 = new javax.swing.JLabel();
        returnButton = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Pandelitos1 = new javax.swing.JButton();
        Homepage = new javax.swing.JButton();
        Pandelitos = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableProductsInCart = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        thankYouLabel.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        thankYouLabel.setText("Thank you for purchasing at Pandelitos!");
        thankYouLabel.setToolTipText("");

        productsPurchasedLabel.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        productsPurchasedLabel.setText("Products purchased:");

        totalPriceLabel.setFont(new java.awt.Font("Serif", 0, 12)); // NOI18N
        totalPriceLabel.setText("Total price:");

        purchaseConfirmedLabel1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        purchaseConfirmedLabel1.setText("Purchase confirmed!");

        returnButton.setText("Return");
        returnButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        returnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                returnButtonActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 144, 0));

        Pandelitos1.setBackground(new java.awt.Color(255, 144, 0));
        Pandelitos1.setFont(new java.awt.Font("Serif", 0, 14)); // NOI18N
        Pandelitos1.setText("Freshly Baked Hand Rolled Pandesal");
        Pandelitos1.setBorder(null);
        Pandelitos1.setBorderPainted(false);
        Pandelitos1.setContentAreaFilled(false);

        Homepage.setBackground(new java.awt.Color(255, 144, 0));
        Homepage.setForeground(new java.awt.Color(255, 144, 0));
        Homepage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pandelitosecommercewebsite/Images/SmallPandelitos.jpg"))); // NOI18N
        Homepage.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Homepage.setBorderPainted(false);
        Homepage.setContentAreaFilled(false);
        Homepage.setMaximumSize(new java.awt.Dimension(100, 100));
        Homepage.setMinimumSize(new java.awt.Dimension(100, 100));
        Homepage.setPreferredSize(new java.awt.Dimension(100, 100));

        Pandelitos.setBackground(new java.awt.Color(255, 144, 0));
        Pandelitos.setFont(new java.awt.Font("Serif", 1, 28)); // NOI18N
        Pandelitos.setText("Pandelitos");
        Pandelitos.setBorder(null);
        Pandelitos.setBorderPainted(false);
        Pandelitos.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(Homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pandelitos)
                    .addComponent(Pandelitos1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(Homepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Pandelitos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pandelitos1)
                .addGap(15, 15, 15))
        );

        TableProductsInCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Product Amount", "Product Price"
            }
        ));
        jScrollPane2.setViewportView(TableProductsInCart);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(productsPurchasedLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 619, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(104, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 304, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(purchaseConfirmedLabel1)
                        .addGap(364, 364, 364))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(thankYouLabel)
                        .addGap(157, 157, 157)
                        .addComponent(returnButton)
                        .addGap(52, 52, 52))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(661, Short.MAX_VALUE)
                .addComponent(totalPriceLabel)
                .addGap(171, 171, 171))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(purchaseConfirmedLabel1)
                .addGap(11, 11, 11)
                .addComponent(productsPurchasedLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalPriceLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(returnButton)
                        .addGap(51, 51, 51))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(thankYouLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void returnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_returnButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new HomePage().setVisible(true);
    }//GEN-LAST:event_returnButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConfirmationPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConfirmationPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Homepage;
    private javax.swing.JButton Pandelitos;
    private javax.swing.JButton Pandelitos1;
    private javax.swing.JTable TableProductsInCart;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel productsPurchasedLabel;
    private javax.swing.JLabel purchaseConfirmedLabel1;
    private javax.swing.JButton returnButton;
    private javax.swing.JLabel thankYouLabel;
    private javax.swing.JLabel totalPriceLabel;
    // End of variables declaration//GEN-END:variables
}
